name: Deploy Frontend and Backend

on:
  push:
    branches: master
    
jobs:
  backend:
    runs-on: macos-11
    steps:
    - run: curl https://cli-assets.heroku.com/install.sh | sh
    - uses: actions/checkout@v2
    - name: push backend
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: 362888a7-4656-417e-bd00-18bdd40fb8d2
        heroku_app_name: "librarysystem07-backend-ls07"
        heroku_email: "samantha.handal@mail.mcgill.ca"
        dontuseforce: false
  frontend:
    needs: backend
    runs-on: macos-11
    steps:
      - run: curl https://cli-assets.heroku.com/install.sh | sh
      - uses: actions/checkout@v2
      - name: push frontend
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 362888a7-4656-417e-bd00-18bdd40fb8d2
          heroku_app_name: "librarysystem07-frontend-ls07"
          heroku_email: "rebecca.mizrahi@mail.mcgill.ca"
          dontuseforce: false
